version: '3.9'

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=elliott@zenful.cloud"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    # image: edmaralencar/boilerplate:latest
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.guestbook-ratelimit.ratelimit.average=20"
      - "traefik.http.routers.server.rule=Host(`edmaralencar.com.br`) && !Method(`POST`)"
      - "traefik.http.services.server.loadbalancer.server.port=8080"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
      - "traefik.http.routers.server.middlewares=server-ratelimit"
      # Define separate router for POST methods
      - "traefik.http.middlewares.server-ratelimit-post.ratelimit.average=1"
      - "traefik.http.middlewares.server-ratelimit-post.ratelimit.period=1m"
      - "traefik.http.routers.server-post.rule=Host(`edmaralencar.com.br`) && Method(`POST`)"
      - "traefik.http.routers.server-post.middlewares=server-ratelimit-post"
      - "traefik.http.routers.server-post.entrypoints=websecure"
      - "traefik.http.routers.server-post.tls.certresolver=myresolver"
      # Proxy
      - "traefik.http.routers.proxy.rule=Host(`edmaralencar.com.br`)"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls.certresolver=myresolver"
    deploy:
      mode: replicated
      replicas: 3
    restart: always

volumes:
  letsencrypt: