name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  commit-hash:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit.outputs.commit_hash }}

    steps:
      - uses: actions/checkout@v4
      - name: Get commit hash
        id: get_commit
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

  build-and-push-image:
    needs:
      - commit-hash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}       
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/boilerplate:${{ needs.commit-hash.outputs.commit_hash }}

  deploy:
    runs-on: ubuntu-latest

    needs:
      - build-and-push-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          touch .env
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> .env

      - name: Deploy to vps
        uses: cssnr/stack-deploy-action@v1
        with:
          name: 'server'
          file: 'docker-compose.yaml'
          host: edmaralencar.com.br
          user: admin
          ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          env_file: './env'
        # uses: appleboy/ssh-action@v1.2.0
        # with:
        #   debug: true
        #   host: "edmaralencar.com.br"
        #   username: "admin"
        #   key: ${{ secrets.DEPLOY_SSH_KEY }}
        #   port: 22
        #   script: |
        #     cd ${{ github.event.repository.name }}
        #     git pull origin main
        #     docker compose up -d --build